
package trabalho01;

import javax.swing.JOptionPane;

/**
 *
 * @author henri
 */
public class Depositar extends javax.swing.JFrame {

    /**
     * Creates new form Depositar
     */
    public Depositar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEPOSITO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Conta:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Valor:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtNum))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        if(txtValor.getText().equals("")||txtNum.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos.");
        }else{
            if(txtNum.getText().matches("[A-Z]*") ||txtValor.getText().matches("[A-Z]*")|| txtNum.getText().matches("[a-z]*") ||txtValor.getText().matches("[a-z]*")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos corretamente.");
        } else{   
            
            double valor = Double.parseDouble(txtValor.getText());
            int cont = Integer.parseInt(txtNum.getText());
           
            if (cont != CadContas.c.getNumero()
                && cont != CadContPoupanca.p.getNumero()
                && cont != CadContEspecial.e.getNumero()){
                JOptionPane.showMessageDialog(null,"Conta não cadastrada no sistema.");
            }
            
            else if(cont == CadContas.c.getNumero()){
               
                Object[] btn= {"Confirmar","Cancelar" };
            int resposta = JOptionPane.showOptionDialog(null,"Senhor(a) "+CadContas.c.getNome()+"\nDeseja confirmar o depósito:","Confirmar",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,btn,btn[0]);
            if(resposta == 0) {
                 CadContas.c.setSaldo(CadContas.c.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this,"Depósito efetuado com sucesso.");
                 dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this,"Depósito cancelado com sucesso.");
                dispose();    
                       }          
            }
            else if(cont == CadContPoupanca.p.getNumero()){
                Object[] btn= {"Confirmar","Cancelar" };
                int resposta = JOptionPane.showOptionDialog(null,"Senhor(a) "+CadContPoupanca.p.getNome()+"\nDeseja confirmar o depósito:","Confirmar",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null,btn,btn[0]);
            if(resposta == 0) {
                
                 CadContPoupanca.p.setSaldo(CadContPoupanca.p.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this,"Depósito efetuado com sucesso");
                 dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this,"Depósito cancelado com sucesso");
                    dispose();    
                        }           
            } 
            else if(cont == CadContEspecial.e.getNumero()){
                Object[] btn={"Confirmar","Cancelar"};
            int resposta = JOptionPane.showOptionDialog(null,"Senhor(a) "+CadContEspecial.e.getNome()+"\nDeseja confirmar o depósito:","Confirmação",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,btn,btn[0]);
            if(resposta == 0) {
                
                 CadContEspecial.e.setSaldo(CadContEspecial.e.getSaldo() + valor);
                 JOptionPane.showMessageDialog(this,"Depósito efetuado com sucesso");
                dispose();
            }
                else if(resposta==1){
                    JOptionPane.showMessageDialog(this,"Depósito cancelado com sucesso");
                dispose();    
                }
            }                      
            this.setVisible(false);
            dispose();
        }
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Depositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
